### ISSUE TITLE
Windows font_dir

### ISSUE THREAD

**Issue by GustavoPeredo** [dirs-dev/dirs-rs#37]
Currently `dirs-rs` returns always None for a font directory in Windows:
```
pub fn font_dir()       -> Option<PathBuf> { None }
```

However, according to this ![issue](https://github.com/matplotlib/matplotlib/issues/12954/), ever since Windows 1809, there has been support for a user font directory.

---

I have written a fork of dirs-sys-rs with support for the folder ![here](https://github.com/GustavoPeredo/dirs-sys-rs), basically it tries to find the directory `%userprofile%\AppData\Local\Microsoft\Windows\Fonts`, if it doesn't exist, the function returns None. Is this a good approach for a merge request?

**Comment by soc** [comment]
Hey Gustavo,

thanks for your contribution!

If Windows made these improvements this would be really great news – I'll try to read through things and try to gain a better understanding.

My first instinct would be to check whether there is a appropriate Win32 API call for it – the general approach of the library is to avoid hitting the file system for various reasons (see second point in https://github.com/dirs-dev/dirs-rs#design-goals).

So I wouldn't try to use the presence or absence of this directory as an indication for anything; I'd probably have a look at whatever the Win32 API does and think whether this is appropriate for this library.

Do you have an idea whether the `winapi` crate provides an appropriate binding? Otherwise I can check and maybe talk to its maintainer to add support for it, and then we can make use of that.

Cheers,

Simon

**Comment by GustavoPeredo** [comment]
Thanks for your answer Simon.
I did some research and there is no win32 api to call for the user's fonts directory.

The general solution seems to be to look at the registry for the directory (![matplotlib](https://github.com/JanSellner/matplotlib/commit/1fd871fb68cc0c241d00a88205d1a3f16326a655) and ![r-lib systemfonts](https://github.com/r-lib/systemfonts/commit/d84906b925a1c11661d8afc7ab74fdc83e7a8c7d)), could this perhaps be a fit for ![dirs-dev/directories](https://github.com/dirs-dev/directories-rs)?

Pro: Availability of another directory for users
Con: Doesn't make use of ![the Known Folder API on Windows](https://github.com/dirs-dev/directories-rs#Introduction)

**Comment by soc** [comment]
Ah interesting! I didn't expect that the registry key was the "intended" way to use the folder (in general I have the impression that they want to avoid introducing public-facing registry things as much as possible) – that's why I assumed there was a Win32 API available. I'm really curious why the known folder API wasn't updated. :-/

**Comment by GustavoPeredo** [comment]
If I had to guess the API hasn't been update to maintain backwards compatibility...

**Comment by soc** [comment]
Based on https://stackoverflow.com/questions/70526705/why-was-the-user-font-directory-not-added-to-the-knownfolder-api I'll (sadly) close this.

It appears that this directory is neither required nor sufficient to do anything userfont-wise.

Feel free to reopen if you have more ideas how to tackle this.

**Comment by GustavoPeredo** [comment]
Thanks for looking into it
